# Generated by Django 2.1.5 on 2020-09-04 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20200903_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Upazila',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.District')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Division')),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='university_Name',
            field=models.CharField(choices=[('Bangladesh Agricultural University', 'Bangladesh Agricultural University'), ('Hajee Mohammad Danesh Science and Technology University', 'Hajee Mohammad Danesh Science and Technology University'), ('Khulna University', 'Khulna University'), ('Noakhali Science and Technology University', 'Noakhali Science and Technology University'), ('Patuakhali Science & Technology University', 'Patuakhali Science & Technology University'), ('University of Rajshahi', 'University of Rajshahi'), ('Sher-e-Bangla Agricultural University', 'Sher-e-Bangla Agricultural University'), ('Sylhet Agricultural University', 'Sylhet Agricultural University'), ('Others', 'Others')], max_length=100),
        ),
        migrations.AddField(
            model_name='district',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Division'),
        ),
        migrations.AddField(
            model_name='person',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.District'),
        ),
        migrations.AddField(
            model_name='person',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.Division'),
        ),
        migrations.AddField(
            model_name='person',
            name='upazila',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.Upazila'),
        ),
    ]
